### ISSUE TITLE
setting root page while being offline

### ISSUE THREAD

**Issue by jose2007kj** [javebratt/event-tutorial#1]
sir,
the app works correctly when i am having internet but when i opens the app without net connection i am getting blank page....so sir how to save the user details first time (on successfull login) to local storage so that app can work correctly while being offline.

**Comment by jose2007kj** [comment]
its working perfectly right....it was my mistake...

**Comment by javebratt** [comment]
Hey @jose2007kj want to share what that mistake was?

**Comment by jose2007kj** [comment]
the mistake i made was.....i modified the code to disable the splash screen and it resulted in some error ....and it was the reaseon i got the blank page...and i realised my mistake  after trying  to run again from unmodified code..

**Comment by javebratt** [comment]
@jose2007kj that happened to me twice, instead of setting the splascreen timeout to 0 I set it to null and it broke everything :P
