### ISSUE TITLE
Promises error

### ISSUE THREAD

**Issue by FonMaestro** [javebratt/event-tutorial#3]
Hello,

first of all. Amazing work. 
Thanks to you I started to learn ionic.

When i login or sign up i have this error

![captura de pantalla 2016-12-18 a la s 18 28 45](https://cloud.githubusercontent.com/assets/908483/21295198/180d7f12-c550-11e6-9896-84ed30cb30ac.png)

Thank you!

**Comment by javebratt** [comment]
Ionic just updated to RC4, I updated my book today and going to move to this course on Tuesday or Wednesday.
