### ISSUE TITLE
Error after logging in

### ISSUE THREAD

**Issue by mediamaxdk** [javebratt/event-tutorial#4]
i ran npm install and then ionic serve, registered and set up an event.

problem is right after logging in, error is displayed but can be dismissed by pressing close.

<img width="429" alt="skaermbillede 2016-12-21 kl 13 45 28" src="https://cloud.githubusercontent.com/assets/10639946/21389887/4753004a-c784-11e6-8efd-963fb106f0da.png">

**Comment by javebratt** [comment]
Yeah, I haven't had time to update the course, because of the holidays, but will get to it this year, there  are breaking changes in the latest releases of `@ionic/app-scripts`

**Comment by mediamaxdk** [comment]
another serious bug there also.

I changed the firebase keys to my own account to test it out.  Registered fine, dismissed the login bug, and then verified in firebase that a new auth user was set up and userProfile had the entry with uid and email.  so far so good.

Then tried editing profile… a bunch of first run errors that would not allow me to edit names and birthDate. but somehow I ended up getting a second userProfile with only names and birthDate, while email was left in the original userProfile.  (see screenshots from firebase)
Tried logging out and back in, but for some reason the n10lS... authUser gets the userProfile for UJey... - which is the UID of a preexisting authUser.

I would expect the UID to be key so I wonder how I can log in as n10IS and get the profile for UJey.
Your app created the userProfile table so there was nothing there before. 

A 3rd user (NXihW…) created, who added an event BEFORE going to profile, this user did not loose the UID and was able to edit all profile info.


Another small detail… when creating events you would want dates in the future instead of past - the spinner stops at 2016 like the birthDate one.

Anyways, I hope you can figure out the bugs :-)  thank you for a great course.

**Comment by squierll** [comment]
I've got the same problem.

**Comment by javebratt** [comment]
Will be updating the course to match RC5 over the weekend.

**Comment by javebratt** [comment]
Just updated this app to RC5 and latest Firebase version, unsubscribed from the auth state since that was causing promise breaking problems.

Gonna close the issue but feel free to open it if the errors persist.
