### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by peterennis** [javebratt/event-tutorial#7]
This is Russian but it means "Error".
Not exactly a "typo"...

![capture931](https://user-images.githubusercontent.com/140737/29197538-008cd7f2-7df1-11e7-91dd-422a59d9ed1a.png)

**Comment by javebratt** [comment]
I don't understand this issue, what's the point?

**Comment by peterennis** [comment]
Book readers are typically English speaking not Russian.
The message would be better in English.

**Comment by javebratt** [comment]
It is in English, that's an old pull request someone made to fix a bug, he had the word in Russian but in a later commit I changed it to English again
